16 implement photonvision tracking system
NorthernForce/Reefscape pull request #67
Opened 2024-11-13 23:46 UTC by Whiteheatzack

2024-12-17 15:24 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/vision/Vision.java
> +import static frc.robot.subsystems.vision.VisionConstants.*;
Please no imports of constants. Try to make constants a parameter

2024-12-17 15:29 UTC, cml1010101 commented
> Looks good other than the one comment I left. I have some constants for you though

Each camera is 13.731 inches X and Y, and 11.248 off of the ground. They are facing 45 degrees from each side (on the corners) and 10 degrees up. No roll.

2024-12-19 13:36 UTC, cml1010101 commented on src/main/java/frc/robot/robots/ZippyContainer.java
> +			vision = new Vision(drive::addVisionMeasurement, ZippyConstants.visionConstants,
This is good

2024-12-19 13:36 UTC, cml1010101 commented on src/main/java/frc/robot/robots/ZippyContainer.java
> +	private final Drive drive = new Drive(null, 0, 0, 0, 0, 0, null, new ModuleIO[0]);
We will have to reconcile with everett's code at some point

2024-12-19 13:36 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/vision/Vision.java
> +	public Vision(VisionConsumer consumer, VisionConstants visionConstants, VisionIO... io)
Nice.

2024-12-19 13:36 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/vision/VisionIOInputs.java
> +public class VisionIOInputs
I think this class is unnecessary.

2024-12-19 13:36 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/vision/VisionIO.java
> +public interface VisionIO
Maybe some javadocs. Looks good otherwise

2024-12-19 13:36 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/vision/VisionIOPhotonVision.java
Really good

2024-12-19 13:36 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/vision/VisionIOPhotonVisionSim.java
Looks fine, but maybe some testing.

2024-12-19 13:36 UTC, cml1010101 commented on src/main/java/frc/robot/util/VisionConstants.java
> +public record VisionConstants(AprilTagFieldLayout aprilTagLayout, double maxAmbiguity, double maxZError,
Perfect

2024-12-19 13:36 UTC, cml1010101 commented on vendordeps/photonlib.json
Please remove. The dependency is unnecessary

2024-12-19 13:47 UTC, Whiteheatzack commented
I’m in a study hall >:(

2024-12-19 13:48 UTC, cml1010101 commented
I'm in APUSH rn, but I'm treating it like a study hall ;)

2025-01-08 14:23 UTC, cml1010101 submitted a review, later dismissed
Make sure to add your code to ZippyContainer

2025-01-12 03:33 UTC, cml1010101 requested changes
Add some javadocs, and this looks ready to test

2025-01-12 13:23 UTC, cml1010101 commented
You should also use the 2025 apriltags, now that I have updated devel to 2025.2.1.

2025-01-12 15:05 UTC, cml1010101 requested changes

2025-01-12 15:05 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/phoenix6/PhoenixCommandDrive.java
You shouldn't need to create a pose estimator. These functions already exist in the superclass, and pose estimator is built in to SwerveDrivetrain

2025-01-12 15:15 UTC, Whiteheatzack commented on src/main/java/frc/robot/subsystems/phoenix6/PhoenixCommandDrive.java
Ohhh, I was wondering about that lol

2025-01-14 14:13 UTC, cml1010101 requested changes

2025-01-14 14:13 UTC, cml1010101 commented on src/main/java/frc/robot/zippy/constants/ZippyConstants.java
> +	private static Transform3d robotToCamera0 = new Transform3d(0.3487674, -0.3487674, 0.2856992,
If measurements are in degrees/inches, could you use Rotation2d with WPI units

2025-01-15 14:49 UTC, cml1010101 requested changes
Remember, angles are counterclockwise. Left is positive Y.

2025-01-15 14:49 UTC, cml1010101 commented on src/main/java/frc/robot/zippy/constants/ZippyConstants.java
> +			Inches.of(11.248), new Rotation3d(Degrees.of(0.0), Degrees.of(10.0), Degrees.of(45.0)));
I think your angles are flipped

2025-01-15 17:47 UTC, Whiteheatzack commented on src/main/java/frc/robot/zippy/constants/ZippyConstants.java
> +			Inches.of(11.248), new Rotation3d(Degrees.of(0.0), Degrees.of(10.0), Degrees.of(45.0)));
But the front left camera is pointed 45º counterclockwise, correct?

2025-01-30 12:31 UTC, closed without merging