95 pneumatic hub subsystem
NorthernForce/Reefscape pull request #96
Opened 2024-12-31 00:16 UTC by Daboss-1

2025-01-12 03:15 UTC, cml1010101 commented
I think some files, moved. Can u fix the merge conflicts @Daboss-1?

2025-01-12 03:38 UTC, cml1010101 requested changes
Can you also add Javadocs everywhere

2025-01-12 03:38 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/pneumatic/PneumaticHub.java
> +		Logger.processInputs("Pneumatics/PneumaticHub", m_inputs);
Why not just have getName() instead of "Pneumatics/PneumaticsHub"

2025-01-14 20:06 UTC, Daboss-1 commented
> Can you also add Javadocs everywhere

Good?

2025-01-14 22:33 UTC, cml1010101 requested changes
Also, please add this to ZippyContainer

2025-01-14 22:33 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/pneumatic/PneumaticHub.java
> +		Logger.processInputs(m_io.getName(), m_inputs);
No not m_io.getName() just do getName() subsystems have names that default to class name, but can be set if need be (For example, if overrided)

2025-01-14 22:33 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/pneumatic/PneumaticHub.java
> +	public void periodic()
Add `@Override`

2025-01-14 22:33 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/pneumatic/PneumaticHubIORev.java
> +	@Override
Unnecessary

2025-01-14 22:33 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/pneumatic/PneumaticHubIO.java
> +	 */
This is not what I wanted. Subsystem has getName(). IO doesn't need name

2025-01-14 22:33 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/pneumatic/PneumaticHubIO.java
> +	 */
Also NO EMOJIS

2025-01-14 22:33 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/pneumatic/PneumaticHub.java
> +public class PneumaticHub extends SubsystemBase
Just some javadocs here

2025-01-14 22:33 UTC, cml1010101 commented on src/main/java/frc/robot/util/PneumaticConstants.java
> +public record PneumaticConstants(int canId, double minPressure, double maxPressure) {
Javadocs here too

2025-01-16 23:41 UTC, Daboss-1 commented on src/main/java/frc/robot/subsystems/pneumatic/PneumaticHubIO.java
> +	 */
But I LOVE emojis

2025-01-16 23:41 UTC, Daboss-1 commented on src/main/java/frc/robot/subsystems/pneumatic/PneumaticHubIO.java
> +	 */
Please

2025-01-16 23:47 UTC, Daboss-1 commented on src/main/java/frc/robot/subsystems/pneumatic/PneumaticHubIO.java
> +	 */
Amendment 30 says "All may have equal access to computer generated emojis and icons if it suits the manner 👍"

2025-01-16 23:49 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/pneumatic/PneumaticHubIO.java
> +	 */
Amendment 30 to what?

2025-01-16 23:56 UTC, Daboss-1 commented on src/main/java/frc/robot/subsystems/pneumatic/PneumaticHubIO.java
> +	 */
Umm, the constitution obviously

2025-01-16 23:57 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/pneumatic/PneumaticHubIO.java
> +	 */
NO EMOJIS.

2025-01-16 23:57 UTC, Daboss-1 commented on src/main/java/frc/robot/subsystems/pneumatic/PneumaticHubIO.java
> +	 */
Oh and I'm pretty sure that 31 says "especially in GitHub and FRC robotics code"

2025-01-16 23:59 UTC, cml1010101 commented on src/main/java/frc/robot/subsystems/pneumatic/PneumaticHubIO.java
> +	 */
I'm pretty sure 32 says Everett is the exception to the aforementioned amendments

2025-01-17 00:27 UTC, Daboss-1 commented on src/main/java/frc/robot/subsystems/pneumatic/PneumaticHubIO.java
> +	 */
But 33 quite clearly states that unless the accuser was rendered by the name of Connor Lund

2025-02-03 19:16 UTC, closed without merging